import {
	SiGnubash,
	SiJavascript,
	SiJson,
	SiReact,
	SiSvelte,
	SiTypescript,
	SiCplusplus,
	SiC,
	SiPostgresql,
	SiPython,
	SiPhp,
	SiRust,
	SiCss,
	SiHtml5,
	SiGo,
	SiKotlin,
	SiMarkdown,
	SiDocker,
	SiMdx
} from '@icons-pack/svelte-simple-icons';

export {
	SiGnubash as bash,
	SiJavascript as js,
	SiJson as json,
	SiReact as jsx,
	SiReact as tsx,
	SiSvelte as svelte,
	SiTypescript as ts,
	SiCplusplus as cpp,
	SiC as c,
	SiPostgresql as sql,
	SiPython as py,
	SiPhp as php,
	SiRust as rs,
	SiCss as css,
	SiHtml5 as html,
	SiGo as go,
	SiKotlin as kt,
	SiMarkdown as markdown,
	SiDocker as dockerfile,
	SiDocker as docker,
	SiMdx as mdx,
	SiMarkdown as md
};
